### ISSUE TITLE
peak calling for each metacell

### ISSUE THREAD

**Issue by fl-yu** [dpeerlab/SEACells#20]
Hi Thank you so much for providing such a valuable tool! I have a couple of questions and thank you in advance for your help!
1. I wonder if can I perform peak calling for a pseudo-bulk sample of each metacell?
2. How many cells/fragments of a metacell will be sufficient for a reliable peak calling?
3. Anything else should I pay attention to for this purpose?

**Comment by ManuSetty** [comment]
We recommend the peak calling on all cells and then identifying the subset of peaks that are open in each metacell. You can have a look at the "Open peaks in metacells" for this computation: https://github.com/dpeerlab/SEACells/blob/main/notebooks/SEACell_ATAC_analysis.ipynb

As we describe in our manuscript, using the above approach rather than peak calling on individual metacells gives much better sensitivity. The results are presented in Supplementary Fig. 15 in our bioRxiv preprint here: https://www.biorxiv.org/content/10.1101/2022.04.02.486748v1.full
