### ISSUE TITLE
Peak calling on NFR fragments

### ISSUE THREAD

**Issue by ivanferrreira** [dpeerlab/SEACells#35]
Hi,

Great paper, thanks for developing SEACells! 

I'm trying to follow your approach to peak call on NFR fragments using the following functions in ArchR:
proj <- addGroupCoverages(proj, maxFragmentLength=147)
proj <- addReproduciblePeakSet(proj)
proj <- addPeakMatrix(proj, maxFragmentLength=147, ceiling=10^9)

But when I try to install the modified ArchR pipeline from github directly from the Greeleaf lab I'm getting:
Skipping install of 'ArchR' from a github remote, the SHA1 (https://github.com/GreenleafLab/ArchR/commit/79953a93ae376a500e681aa3b5ba669af6bb58e1) has not changed since last install.

Forcing to install from github results in:
installation of package ‘.../tmp/RtmpM2couO/file28dbc3dd83145/ArchR_1.0.2.tar.gz’ had non-zero exit status

I tried pulling directly from <https://github.com/dpeerlab/ArchR> as well and it didn't work.

Can you help? I'm not sure how to get it otherwise.

Thanks
Ivan

**Comment by christinedien** [comment]
Hi Ivan,

Thank you for using SEACells! 

The SHA1 error typically occurs when there is an existing installation of the same package already since `devtools` tries to prevent reinstalling duplicated packages. If this is the case, have you tried uninstalling and re-installing?

Were you getting the same SHA1 error when pulling from the dpeerlab GitHub or a separate non-zero exit status?

I highly recommend using a package called [renv](https://rstudio.github.io/renv/articles/renv.html) to manage your R environments. It creates a library on a per-project basis and can help avoid installation errors. Installation from GitHub can be done using devtools or :

```
renv::install("GreenleafLab/ArchR")
```

**Comment by ivanferrreira** [comment]
Hi @christinedien - thanks for getting back to me so quickly!

I tried your suggestion, and installed ArchR  ArchR v1.0.2 from the GreenleafLab repository, however none of the versions available include the modified pipeline which allows peak calling on NFR fragments; for instance the addPeakMatrix function does not have a variable to set maxFragmentLength=147, i.e.:

```
Usage:
     addPeakMatrix(
       ArchRProj = NULL,
       ceiling = 4,
       binarize = FALSE,
       verbose = TRUE,
       threads = getArchRThreads(),
       parallelParam = NULL,
       force = TRUE,
       logFile = createLogFile("addPeakMatrix")
     )
```

I tried reaching out to Greenleaf lab (#issue [#1909](https://github.com/GreenleafLab/ArchR/issues/1909)), which recommended me to check with whom forked the modified pipeline. 

Talking with Manu Shetty yesterday,  he recommended me to install ArchR directly from dpeerlab repository, which I did using renv per your suggestion:
renv::install("dpeerlab/ArchR")

I get ArchR v1.0.1 installed, but again I get an ArchR pipeline which the functions **addGroupCoverages** and **addPeakMatrix** lacking the variable **maxFragmentLength**. 

This makes me think that the available pipeline in the dpeerlab github repository does not contain the version used in the SEACells paper. I wonder if you can look into it and make it available so the archr [pre-processing](https://github.com/dpeerlab/SEACells/blob/main/notebooks/ArchR/ArchR-preprocessing-nfr-peaks.R) used in the SEACells paper is reproducible?

**Comment by christinedien** [comment]
Hi Ivan,

On the dpeerlab/ArchR repository, the latest commits have the `maxFragmentLength` as an available parameter. See here for the [`addGroupCoverages`](https://github.com/dpeerlab/ArchR/blob/33042e1b89423a913ccc475434135c9fefa90a94/R/GroupCoverages.R#L38) and the [`addPeakMatrix`](https://github.com/dpeerlab/ArchR/blob/33042e1b89423a913ccc475434135c9fefa90a94/R/MatrixFeatures.R#L120) functions.

After installation using `renv::install("dpeerlab/ArchR")`, you should be able to use these functions. 

The available parameters are not currently updated in the [docstrings](https://github.com/dpeerlab/ArchR/blob/33042e1b89423a913ccc475434135c9fefa90a94/R/MatrixFeatures.R#L102) which is why the output of `help` does not display this. We will fix this ASAP to avoid further confusion -- thank you for bringing this to our attention!

**Comment by ivanferrreira** [comment]
You are right (: thank you!
